name = "forcloudflare"
main = "worker.js"
compatibility_date = "2025-06-13"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[kv_namespaces]]
binding = "SERVER_STATUS"
id = "4d1df7652b954bb7b3bf3f80a98e2e19"
